---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: bento/centos-7.1
  - name: bento/ubuntu-14.04
    run_list:
      - apt

suites:
  - name: default
    run_list:
      - samba4::default
    attributes:
  - name: domain_controller
    run_list:
      - samba4::domain_controller
    attributes:
      domain: kitchen.test
